// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Triumph.SMS.Remote.Persistence.Data;

#nullable disable

namespace Triumph.SMS.Remote.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215203332_AddedStudentMiddleName")]
    partial class AddedStudentMiddleName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Triumph.SMS.Remote.Core.Students.ParentPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentPhones");
                });

            modelBuilder.Entity("Triumph.SMS.Remote.Core.Students.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherNames")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Residence")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Triumph.SMS.Remote.Core.Students.ParentPhone", b =>
                {
                    b.HasOne("Triumph.SMS.Remote.Core.Students.Student", "Student")
                        .WithMany("ParentPhones")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Triumph.SMS.Remote.Core.Common.ValueObjects.Contact", "Contact", b1 =>
                        {
                            b1.Property<int>("ParentPhoneId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("TEXT")
                                .HasColumnName("CountryCode");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("ParentPhoneId");

                            b1.ToTable("ParentPhones");

                            b1.WithOwner()
                                .HasForeignKey("ParentPhoneId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Triumph.SMS.Remote.Core.Students.Student", b =>
                {
                    b.Navigation("ParentPhones");
                });
#pragma warning restore 612, 618
        }
    }
}
